In [1]:
import pandas as pd

In [2]:
import math
import operator
math.sqrt(operator.add(4,5))

3.0

In [3]:
from datascience import *

the above datascience module can be found in the following link 
https://github.com/data-8/datascience 

In [4]:
path_data = 'data/'
import numpy as np 
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [5]:
np.set_printoptions(threshold=50)

In [6]:
cones = Table.read_table(path_data + 'cones.csv')

In [7]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

## show
the table method `show` can be used to show only some rows 

In [8]:
cones.show(2)

## Select
to chose some columns

In [9]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [10]:
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

## drop

In [11]:
no_color = cones.drop('Color')
no_color

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

## sorting

In [12]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [13]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75
chocolate  | light brown | 4.75
strawberry | pink        | 3.55

## where

In [14]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

## NBA salary data

In [15]:
nba = Table.read_table(path_data+'nba_salaries.csv').relabeled(3, 'SALARY')

In [16]:
nba

PLAYER           | POSITION | TEAM          | SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [17]:
hawks = nba.where('TEAM', 'Atlanta Hawks')
hawks

PLAYER           | POSITION | TEAM          | SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (4 rows omitted)

## show

it will show the entire file

In [18]:
hawks.show()

let us see who gets the most salary

In [19]:
nba.sort('SALARY', descending=True)

PLAYER          | POSITION | TEAM                  | SALARY
Kobe Bryant     | SF       | Los Angeles Lakers    | 25
Joe Johnson     | SF       | Brooklyn Nets         | 24.8949
LeBron James    | SF       | Cleveland Cavaliers   | 22.9705
Carmelo Anthony | SF       | New York Knicks       | 22.875
Dwight Howard   | C        | Houston Rockets       | 22.3594
Chris Bosh      | PF       | Miami Heat            | 22.1927
Chris Paul      | PG       | Los Angeles Clippers  | 21.4687
Kevin Durant    | SF       | Oklahoma City Thunder | 20.1586
Derrick Rose    | PG       | Chicago Bulls         | 20.0931
Dwyane Wade     | SG       | Miami Heat            | 20
... (407 rows omitted)

In [20]:
nba.where('SALARY', are.above(22))

PLAYER          | POSITION | TEAM                | SALARY
Joe Johnson     | SF       | Brooklyn Nets       | 24.8949
LeBron James    | SF       | Cleveland Cavaliers | 22.9705
Dwight Howard   | C        | Houston Rockets     | 22.3594
Kobe Bryant     | SF       | Los Angeles Lakers  | 25
Chris Bosh      | PF       | Miami Heat          | 22.1927
Carmelo Anthony | SF       | New York Knicks     | 22.875

In [21]:
nba.where(nba.column('SALARY') > 23)

PLAYER      | POSITION | TEAM               | SALARY
Joe Johnson | SF       | Brooklyn Nets      | 24.8949
Kobe Bryant | SF       | Los Angeles Lakers | 25

## String methods

In [22]:
"hello".upper()

'HELLO'

In [23]:
"abdul baqi".replace('baqi', 'aziz')

'abdul aziz'

## Array

In [24]:
pos = make_array("verb", 'noun', 'adjective', 'pronoun', 'adverb')

In [25]:
pos

array(['verb', 'noun', 'adjective', 'pronoun', 'adverb'], dtype='<U9')

In [26]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [27]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

## array functions

In [28]:
highs.size

4

In [29]:
highs.sum()

57.736000000000004

In [30]:
highs.mean()

14.434000000000001

## NP array functions

the diff function computes the difference between each adjacent pair of elements in an array. The first element of the diff is the second element minus the first.

In [31]:
np.diff(highs)

array([0.787, 0.198, 0.579])

In [32]:
np.prod(highs)

43274.231214608

In [33]:
np.sum(highs)

57.736000000000004

check many useful `np` functions in this page:
https://docs.microsoft.com/en-us/learn/modules/introduction-python-using-datascience-library/12-sequences 

## Ranges

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(70, 100)

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
#with steps
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Back to Tables

The with_columns method on a table constructs a new table with additional labeled columns. Each column of a table is an array. To add one new column to a table, call with_columns with a label and an array. (The with_column method can be used with the same effect.)

In [37]:
Table().with_columns('Number of petals', make_array(8,43,9))

Number of petals
8
43
9

In [38]:
flowers = Table().with_columns(
    'Number of petals', make_array(8, 34, 5),
    'Name', make_array('lotus', 'sunflower', 'rose')
)

flowers.with_columns(
    'Color', make_array('pink', 'yellow', 'red')
)

Number of petals | Name      | Color
8                | lotus     | pink
34               | sunflower | yellow
5                | rose      | red

In [39]:
minard = Table.read_table(path_data+'minard.csv')
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

## table properties

In [40]:
minard.num_columns

5

In [41]:
minard.num_rows

8

In [42]:
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [43]:
minard.relabeled('City', 'City name')

Longitude | Latitude | City name   | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [44]:
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

to access data in column

In [45]:
minard.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [46]:
minard.column(3)

array(['Advance', 'Advance', 'Advance', 'Advance', 'Retreat', 'Retreat',
       'Retreat', 'Retreat'], dtype='<U7')

In [47]:
minard.column(1).item(3)

55.8

Because columns are arrays, we can use array operations on them to discover new information. For example, we can create a new column that contains the percent of all survivors at each city after Smolensk.

In [48]:
initial = minard.column('Survivors').item(0)
minard = minard.with_columns('% surviving', minard.column('Survivors')/initial)
minard

Longitude | Latitude | City        | Direction | Survivors | % surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

In [49]:
minard.set_format('% surviving', PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | % surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

## select columns

In [50]:
minard.select(0,1)

Longitude | Latitude
32        | 54.8
33.2      | 54.9
34.4      | 55.5
37.6      | 55.8
34.3      | 55.2
32        | 54.6
30.4      | 54.4
26.8      | 54.3

In [51]:
minard.drop(2,4)

Longitude | Latitude | Direction | % surviving
32        | 54.8     | Advance   | 100.00%
33.2      | 54.9     | Advance   | 96.55%
34.4      | 55.5     | Advance   | 87.66%
37.6      | 55.8     | Advance   | 68.97%
34.3      | 55.2     | Retreat   | 37.93%
32        | 54.6     | Retreat   | 16.55%
30.4      | 54.4     | Retreat   | 13.79%
26.8      | 54.3     | Retreat   | 8.28%

In [52]:
nba

PLAYER           | POSITION | TEAM          | SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [53]:
nba.sort('SALARY', descending=True).select(0).show(20)

## Take

In [54]:
nba.take(2)

PLAYER         | POSITION | TEAM          | SALARY
Tiago Splitter | C        | Atlanta Hawks | 9.75625

In [55]:
nba.take(range(3,9))

PLAYER          | POSITION | TEAM          | SALARY
Jeff Teague     | PG       | Atlanta Hawks | 8
Kyle Korver     | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha | SF       | Atlanta Hawks | 4
Mike Scott      | PF       | Atlanta Hawks | 3.33333
Kent Bazemore   | SF       | Atlanta Hawks | 2
Dennis Schroder | PG       | Atlanta Hawks | 1.7634

In [56]:
nba.sort(3, descending=True).take(range(5))

PLAYER          | POSITION | TEAM                | SALARY
Kobe Bryant     | SF       | Los Angeles Lakers  | 25
Joe Johnson     | SF       | Brooklyn Nets       | 24.8949
LeBron James    | SF       | Cleveland Cavaliers | 22.9705
Carmelo Anthony | SF       | New York Knicks     | 22.875
Dwight Howard   | C        | Houston Rockets     | 22.3594

In [60]:
nba.where('TEAM', are.equal_to('Golden State Warriors')).show()

In [62]:
nba.where('TEAM', 'Denver Nuggets') # equivalent to nba.where('Team', are.equal_to('Denver Nuggets'))

PLAYER            | POSITION | TEAM           | SALARY
Danilo Gallinari  | SF       | Denver Nuggets | 14
Kenneth Faried    | PF       | Denver Nuggets | 11.236
Wilson Chandler   | SF       | Denver Nuggets | 10.4494
JJ Hickson        | C        | Denver Nuggets | 5.6135
Jameer Nelson     | PG       | Denver Nuggets | 4.345
Will Barton       | SF       | Denver Nuggets | 3.53333
Emmanuel Mudiay   | PG       | Denver Nuggets | 3.10224
Darrell Arthur    | PF       | Denver Nuggets | 2.814
Jusuf Nurkic      | C        | Denver Nuggets | 1.842
Joffrey Lauvergne | C        | Denver Nuggets | 1.70972
... (4 rows omitted)

In [66]:
nba.where('POSITION', 'C').where('SALARY', are.above(10)).show()

In [68]:
nba.where('TEAM', are.containing('Warriors')).show()

## reading data from online

In [69]:
# As of Jan 2017, this census file is online here: 
data = 'http://www2.census.gov/programs-surveys/popest/datasets/2010-2015/national/asrh/nc-est2015-agesex-res.csv'

# A local copy can be accessed here in case census.gov moves the file:
# data = path_data + 'nc-est2015-agesex-res.csv'

full_census_table = Table.read_table(data)
full_census_table

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015
0    | 0    | 3944153       | 3944160           | 3951330         | 3963087         | 3926540         | 3931141         | 3949775         | 3978038
0    | 1    | 3978070       | 3978090           | 3957888         | 3966551         | 3977939         | 3942872         | 3949776         | 3968564
0    | 2    | 4096929       | 4096939           | 4090862         | 3971565         | 3980095         | 3992720         | 3959664         | 3966583
0    | 3    | 4119040       | 4119051           | 4111920         | 4102470         | 3983157         | 3992734         | 4007079         | 3974061
0    | 4    | 4063170       | 4063186           | 4077551         | 4122294         | 4112849         | 3994449         | 4005716         | 4020035
0    | 5    | 4056858       | 4056872           | 4064653         | 4087709         | 4132242         | 4123626         | 4006900         | 4018158
0    | 6    | 4066381       | 4066412           | 4073013         | 4074993         | 4097605         | 4142916         | 4135930         | 4019207
0    | 7    | 4030579       | 4030594           | 4043046         | 4083225         | 4084913         | 4108349         | 4155326         | 4148360
0    | 8    | 4046486       | 4046497           | 4025604         | 4053203         | 4093177         | 4095711         | 4120903         | 4167887
0    | 9    | 4148353       | 4148369           | 4125415         | 4035710         | 4063152         | 4104072         | 4108349         | 4133564
... (296 rows omitted)

in the above table, let us create a new column to record the percentage change in population between 2010 and 2015.

In [81]:
#first create a smaller table
partial_table = full_census_table.select('SEX','AGE','POPESTIMATE2010', 'POPESTIMATE2015')
# partial_table

#RENAME
partial_table = partial_table.relabeled('POPESTIMATE2010', '2010').relabeled('POPESTIMATE2015', '2015')
# partial_table
# now let us see the change
change = partial_table.column('2015')- partial_table.column('2010')

#now add to the file
us_pop = partial_table.with_columns('change',change,
    'percent change', change/partial_table.column('2010'))
us_pop.set_format('percent change', PercentFormatter)
us_pop

SEX  | AGE  | 2010    | 2015    | change  | percent change
0    | 0    | 3951330 | 3978038 | 26708   | 0.68%
0    | 1    | 3957888 | 3968564 | 10676   | 0.27%
0    | 2    | 4090862 | 3966583 | -124279 | -3.04%
0    | 3    | 4111920 | 3974061 | -137859 | -3.35%
0    | 4    | 4077551 | 4020035 | -57516  | -1.41%
0    | 5    | 4064653 | 4018158 | -46495  | -1.14%
0    | 6    | 4073013 | 4019207 | -53806  | -1.32%
0    | 7    | 4043046 | 4148360 | 105314  | 2.60%
0    | 8    | 4025604 | 4167887 | 142283  | 3.53%
0    | 9    | 4125415 | 4133564 | 8149    | 0.20%
... (296 rows omitted)